Repository black-parrot/black-parrot, pull requests merged in 2020-11, with the labels that each got.

#659 Adding bp_finish at the end of test
  bp_common/test/src/demos/src/sample.c
Labels: software

#658 Fixing Weird Cache Configs
  .gitlab-ci.yml
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
  bp_common/src/include/bp_common_aviary_pkg.vh
  bp_common/syn/Makefile.dc
  bp_fe/src/v/bp_fe_icache.v
  bp_me/src/v/cache/bp_me_cce_to_cache.v
  bp_me/src/v/cce/bp_cce_loopback.v
  bp_me/src/v/lce/bp_lce.v
  bp_me/src/v/lce/bp_lce_cmd.v
  bp_me/src/v/lce/bp_lce_req.v
  bp_top/src/v/bp_cfg.v
  bp_top/src/v/bp_clint_slice.v
  bp_top/src/v/bp_tile.v
  bp_top/src/v/bp_unicore.v
  bp_top/test/common/bp_nonsynth_cache_tracer.v
  bp_top/test/common/bp_nonsynth_if_verif.v
  bp_top/test/tb/bp_tethered/Makefile.cfgs
  ci/weird_config.sh
Labels: bug

#662 Harden predictors
  bp_common/src/include/bp_common_aviary_pkg.vh
  bp_fe/src/include/bp_fe_defines.vh
  bp_fe/src/v/bp_fe_bht.v
  bp_fe/src/v/bp_fe_btb.v
  bp_fe/src/v/bp_fe_pc_gen.v
Labels: ppa_low

#663 Adding full tag info to the cache service interface
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
  bp_be/src/v/bp_be_top.v
  bp_be/test/tb/bp_be_dcache/testbench.v
  bp_be/test/tb/bp_be_dcache/wrapper.v
  bp_common/src/include/bp_common_cache_service_if.vh
  bp_me/src/v/cce/bp_uce.v
  bp_me/src/v/lce/bp_lce.v
  bp_me/src/v/lce/bp_lce_cmd.v
Labels: enhancement

#665 Fixing up synchronization sequence in LCEs
  bp_common/src/include/bp_common_aviary_pkg.vh
  bp_common/test/src/bootrom/bootrom.S
  bp_me/src/v/lce/bp_lce.v
  bp_me/src/v/lce/bp_lce_req.v
  ci/dcache_regress.sh
Labels: bug

#664 Updating dev to fe_dev
  bp_be/src/include/bp_be_ctl_defines.vh
  bp_be/src/include/bp_be_internal_if_defines.vh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
  bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.v
  bp_be/src/v/bp_be_checker/bp_be_director.v
  bp_be/src/v/bp_be_mem/bp_be_csr.v
  bp_be/syn/flist.vcs
  bp_common/src/include/bp_common_aviary_pkg.vh
  bp_common/src/include/bp_common_fe_be_if.vh
  bp_common/src/v/bp_tlb.v
  bp_fe/src/include/bp_fe_defines.vh
  bp_fe/src/include/bp_fe_icache.vh
  bp_fe/src/include/bp_fe_icache_pkg.vh
  bp_fe/src/include/bp_fe_pkg.vh
  bp_fe/src/v/bp_fe_bht.v
  bp_fe/src/v/bp_fe_btb.v
  bp_fe/src/v/bp_fe_icache.v
  bp_fe/src/v/bp_fe_mem.v
  bp_fe/src/v/bp_fe_pc_gen.v
  bp_fe/src/v/bp_fe_top.v
  bp_fe/syn/flist.vcs
  bp_fe/test/tb/bp_fe_icache/Makefile.frag
  bp_fe/test/tb/bp_fe_icache/testbench.v
  bp_fe/test/tb/bp_fe_icache/wrapper.v
  bp_me/src/v/cache/bp_me_cce_to_cache_dma.v
  bp_me/src/v/cce/bp_uce.v
  bp_me/src/v/lce/bp_lce_cmd.v
  bp_me/test/tb/bp_cce/testbench.v
  bp_top/syn/flist.vcs
  bp_top/test/tb/bp_tethered/testbench.v
Labels: update

#666 Update me dev to dev
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
  bp_be/src/v/bp_be_top.v
  bp_be/test/tb/bp_be_dcache/testbench.v
  bp_be/test/tb/bp_be_dcache/wrapper.v
  bp_common/src/include/bp_common_aviary_pkg.vh
  bp_common/src/include/bp_common_cache_service_if.vh
  bp_common/test/src/bootrom/bootrom.S
  bp_fe/src/v/bp_fe_icache.v
  bp_fe/src/v/bp_fe_top.v
  bp_me/src/v/cce/bp_uce.v
  bp_me/src/v/lce/bp_lce.v
  bp_me/src/v/lce/bp_lce_cmd.v
  bp_me/src/v/lce/bp_lce_req.v
  bp_top/src/v/bp_core.v
  bp_top/src/v/bp_unicore.v
  ci/dcache_regress.sh
Labels: update

#667 Sw dev
  .gitlab-ci.yml
  bp_common/syn/Makefile.verilator
  bp_common/test/src/demos/src/sample.c
Labels: update

#670 Minor renames for interfaces
  bp_be/src/include/bp_be_pkg.vh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v
  bp_be/src/v/bp_be_checker/bp_be_director.v
  bp_be/src/v/bp_be_checker/bp_be_issue_queue.v
  bp_be/src/v/bp_be_checker/bp_be_scheduler.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
  bp_be/src/v/bp_be_mem/bp_be_ptw.v
  bp_be/src/v/bp_be_top.v
  bp_be/test/common/bp_be_mock_fe.v
  bp_be/test/tb/bp_be_dcache/wrapper.v
  bp_common/src/include/bp_common_cache_engine_if.vh
  bp_common/src/include/bp_common_core_if.vh
  bp_common/src/include/bp_common_pkg.vh
  bp_common/src/v/bp_tlb.v
  bp_fe/src/include/bp_fe_decompress.vh
  bp_fe/src/include/bp_fe_pkg.vh
  bp_fe/src/v/bp_fe_icache.v
  bp_fe/src/v/bp_fe_pc_gen.v
  bp_fe/src/v/bp_fe_top.v
  bp_fe/test/common/mock/mock_be.v
  bp_fe/test/common/mock/mock_be_tb.v
  bp_fe/test/tb/bp_fe_icache/wrapper.v
  bp_me/src/v/cce/bp_uce.v
  bp_me/src/v/lce/bp_lce.v
  bp_me/src/v/lce/bp_lce_cmd.v
  bp_me/src/v/lce/bp_lce_req.v
  bp_top/src/v/bp_cacc_vdp.v
  bp_top/src/v/bp_core.v
  bp_top/src/v/bp_core_minimal.v
  bp_top/src/v/bp_unicore.v
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_branch_profiler.v
  bp_top/test/common/bp_nonsynth_cache_tracer.v
  bp_top/test/common/bp_nonsynth_if_verif.v
  bp_top/test/common/bp_nonsynth_vm_tracer.v
  bp_top/test/tb/bp_tethered/testbench.v
  docs/interface_specification.md
Labels: clarity

#672 Bump dev to me_dev
  bp_be/src/include/bp_be_pkg.vh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v
  bp_be/src/v/bp_be_checker/bp_be_director.v
  bp_be/src/v/bp_be_checker/bp_be_issue_queue.v
  bp_be/src/v/bp_be_checker/bp_be_scheduler.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
  bp_be/src/v/bp_be_mem/bp_be_ptw.v
  bp_be/src/v/bp_be_top.v
  bp_be/test/common/bp_be_mock_fe.v
  bp_be/test/tb/bp_be_dcache/wrapper.v
  bp_common/src/include/bp_common_cache_engine_if.vh
  bp_common/src/include/bp_common_core_if.vh
  bp_common/src/include/bp_common_pkg.vh
  bp_common/src/v/bp_tlb.v
  bp_fe/src/include/bp_fe_decompress.vh
  bp_fe/src/include/bp_fe_pkg.vh
  bp_fe/src/v/bp_fe_icache.v
  bp_fe/src/v/bp_fe_pc_gen.v
  bp_fe/src/v/bp_fe_top.v
  bp_fe/test/common/mock/mock_be.v
  bp_fe/test/common/mock/mock_be_tb.v
  bp_fe/test/tb/bp_fe_icache/wrapper.v
  bp_me/src/v/cce/bp_uce.v
  bp_me/src/v/lce/bp_lce.v
  bp_me/src/v/lce/bp_lce_cmd.v
  bp_me/src/v/lce/bp_lce_req.v
  bp_top/src/v/bp_cacc_vdp.v
  bp_top/src/v/bp_core.v
  bp_top/src/v/bp_core_minimal.v
  bp_top/src/v/bp_unicore.v
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_branch_profiler.v
  bp_top/test/common/bp_nonsynth_cache_tracer.v
  bp_top/test/common/bp_nonsynth_if_verif.v
  bp_top/test/common/bp_nonsynth_vm_tracer.v
  bp_top/test/tb/bp_tethered/testbench.v
  docs/interface_specification.md
Labels: update

#678 Small fix for burst_to_lite modules
  .gitlab-ci.yml
  bp_me/src/v/wormhole/bp_burst_to_lite.v
  bp_me/src/v/wormhole/bp_lite_to_burst.v
  ci/weird_config.sh
Labels: bug

#676 Adding a compile time check for cache parameter conditions
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
Labels: clarity

#683 Adding assertion for illegal $ configuration
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
  bp_fe/src/v/bp_fe_icache.v
Labels: clarity

#689 Update dev to be_dev
  bp_be/src/include/bp_be_ctl_defines.svh
  bp_be/src/include/bp_be_internal_if_defines.svh
  bp_be/src/include/bp_be_mem_defines.svh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_csr.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv
  bp_be/src/v/bp_be_calculator/bp_be_ptw.sv
  bp_be/src/v/bp_be_checker/bp_be_director.sv
  bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv
  bp_be/src/v/bp_be_checker/bp_be_regfile.sv
  bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf_queue.sv
  bp_be/src/v/bp_be_mem/bp_be_csr.sv
  bp_be/src/v/bp_be_top.sv
  bp_be/syn/flist.vcs
  bp_fe/syn/flist.vcs
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_vm_tracer.sv
Labels: update

#690 Tapeout fixes
  bp_common/src/include/bp_common_aviary_pkg.sv
  bp_fe/src/v/bp_fe_bht.sv
  bp_fe/src/v/bp_fe_btb.sv
Labels: bug
