Repository black-parrot/black-parrot, pull requests merged in 2020-04, with the labels that each got.

#421 Add configs that use FSM CCE, parameterized CCE instantiation
  .gitlab-ci.yml
  bp_common/src/include/bp_common_aviary_defines.vh
  bp_common/src/include/bp_common_aviary_pkg.vh
  bp_me/src/v/cce/bp_cce_fsm.v
  bp_me/src/v/cce/bp_cce_msg.v
  bp_me/src/v/cce/bp_cce_wrapper.v
  bp_me/syn/Makefile
  bp_top/src/v/bp_l2e_tile.v
  bp_top/src/v/bp_tile.v
  bp_top/syn/flist.vcs
  bp_top/test/tb/bp_processor/testbench.v
Labels: enhancement

#429 Fixed sign extension in mul pipe
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mul.v
Labels: bug

#433 Poison the Long Pipe Input
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
Labels: bug

#436 Fixing reserved keyword and prereq requirements
  Makefile
  bp_top/test/common/bp_nonsynth_core_profiler.v
  bp_top/test/tb/bp_processor/testbench.v
  bp_top/test/tb/bp_softcore/testbench.v
Labels: bug

#438 fully specify TB and CFG in CI file for tests
  .gitlab-ci.yml
Labels: bug, testing

#440 Top dev
  bp_be/src/v/bp_be_checker/bp_be_director.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce_req.v
  bp_common/src/include/bp_common_aviary_defines.vh
  bp_common/src/include/bp_common_aviary_pkg.vh
  bp_common/src/include/bp_common_pkg.vh
  bp_common/test/Makefile.frag
  bp_common/test/src/demos/Makefile.frag
  bp_common/test/src/demos/src/cache_flush.c
  bp_fe/test/tb/bp_fe_icache/testbench.v
  bp_me/src/v/cache/bp_me_cache_slice.v
  bp_me/src/v/cache/bp_me_cce_to_cache.v
  bp_me/src/v/cache/bp_me_cce_to_cache_buffered.v
  bp_me/test/tb/bp_cce/testbench.v
  bp_me/test/tb/bp_cce_fsm/testbench.v
  bp_top/src/v/bp_cfg.v
  bp_top/src/v/bp_clint_slice.v
  bp_top/src/v/bp_clint_slice_buffered.v
  bp_top/src/v/bp_l2e_tile.v
  bp_top/src/v/bp_softcore.v
  bp_top/src/v/bp_tile.v
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_nbf_loader.v
  bp_top/test/tb/bp_accelerator_demo/testbench.v
  bp_top/test/tb/bp_processor/testbench.v
  bp_top/test/tb/bp_softcore/testbench.v
Labels: enhancement, ppa_medium

#447 remove write to read forwarding in spec bits
  bp_me/src/v/cce/bp_cce_spec_bits.v
Labels: bug

#448 Brings PC Histogram to Black Parrot
  bp_common/software/py/pc_histogram.py
Labels: enhancement

#449 Extending blood graph timing window options
  bp_common/software/py/blood_graph.py
Labels: enhancement

#451 Add instructions for build on docker
  Dockerfile
  README.md
  docker-compose.yml
Labels: flow
