Repository black-parrot/black-parrot, pull requests merged in 2020-07, with the labels that each got.

#568 Update dev to sw_dev
  bp_top/test/common/bp_nonsynth_cosim.v
  bp_top/test/common/dromajo_cosim.cpp
  bp_top/test/tb/bp_tethered/testbench.v
Labels: update

#569 Update dev from be_dev
  bp_be/src/include/bp_be_ctl_defines.vh
  bp_be/src/include/bp_be_dcache/bp_be_dcache_pkg.vh
  bp_be/src/include/bp_be_dcache_pipeline.vh
  bp_be/src/include/bp_be_dcache_pkg.vh
  bp_be/src/include/bp_be_dcache_pkt.vh
  bp_be/src/include/bp_be_dcache_tag_info.vh
  bp_be/src/include/bp_be_dcache_wbuf_entry.vh
  bp_be/src/include/bp_be_internal_if_defines.vh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
  bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v
  bp_be/src/v/bp_be_calculator/bp_be_int_alu.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_ctrl.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_fp.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_int.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_long.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mul.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.v
  bp_be/src/v/bp_be_calculator/bp_be_regfile.v
  bp_be/src/v/bp_be_checker/bp_be_detector.v
  bp_be/src/v/bp_be_checker/bp_be_director.v
  bp_be/src/v/bp_be_checker/bp_be_scheduler.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_decoder.v
  bp_be/src/v/bp_be_mem/bp_be_ptw.v
  bp_be/src/v/bp_be_top.v
  bp_be/syn/flist.vcs
  bp_be/test/common/bp_be_mock_fe.v
  bp_be/test/common/bp_be_mock_ptw.v
  bp_be/test/common/bp_be_nonsynth_npc_tracer.v
  bp_be/test/common/bp_be_nonsynth_perf.v
  bp_be/test/common/bp_be_nonsynth_vm_tracer.v
  bp_be/test/tb/bp_be_dcache/test_bp.v
  bp_be/test/tb/bp_be_dcache/testbench.v
  bp_be/test/tb/bp_be_dcache/trace_gen.py
  bp_be/test/tb/bp_be_dcache/trace_script.py
  bp_common/software/py/nbf.py
  bp_common/src/include/bp_common_aviary_defines.vh
  bp_common/src/include/bp_common_aviary_pkg.vh
  bp_common/src/include/bp_common_cache_service_if.vh
  bp_common/src/include/bp_common_cfg_link_pkg.vh
  bp_common/src/include/bp_common_rv64_defines.vh
  bp_common/src/include/bp_common_rv64_pkg.vh
  bp_common/src/v/bp_pma.v
  bp_common/src/v/bp_tlb.v
  bp_fe/src/v/bp_fe_instr_scan.v
  bp_fe/src/v/bp_fe_mem.v
  bp_fe/syn/flist.vcs
  bp_me/syn/flist.vcs
  bp_me/test/common/bp_cce_mmio_cfg_loader.v
  bp_top/src/v/bp_cfg.v
  bp_top/src/v/bp_unicore.v
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_host.v
  bp_top/test/tb/bp_tethered/Makefile.params
  bp_top/test/tb/bp_tethered/Makefile.vcs
  bp_top/test/tb/bp_tethered/testbench.v
Labels: update

#576 Removing deprecated header file
  bp_me/src/include/c/bp_cce.h
Labels: clarity

#574 Cleaning up D$ opcodes and decoding
  bp_be/src/include/bp_be_ctl_defines.vh
  bp_be/src/include/bp_be_internal_if_defines.vh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
  bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v
  bp_be/src/v/bp_be_calculator/bp_be_int_alu.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_ctl.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_int.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_long.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v
  bp_be/src/v/bp_be_checker/bp_be_scheduler.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_decoder.v
  bp_be/src/v/bp_be_mem/bp_be_ptw.v
  bp_be/src/v/bp_be_top.v
  bp_be/syn/coverage_hier.vcs
  bp_be/syn/flist.vcs
  bp_fe/syn/coverage_hier.vcs
  bp_fe/syn/flist.vcs
  bp_me/syn/coverage_hier.vcs
  bp_top/src/v/bp_cacc_vdp.v
  bp_top/syn/flist.vcs
  bp_top/test/tb/bp_tethered/testbench.v
Labels: clarity, ppa_low

#579 Move memory response processing out of FSM for CCE's uncached only mode
  bp_me/src/v/cce/bp_cce_msg.v
Labels: bug

#582 Bump dev from me_dev
  bp_be/test/tb/bp_be_dcache/testbench.v
  bp_be/test/tb/bp_be_dcache/wrapper.v
  bp_common/src/include/bp_common_mem_if.vh
  bp_fe/test/tb/bp_fe_icache/testbench.v
  bp_fe/test/tb/bp_fe_icache/wrapper.v
  bp_me/src/asm/include/bp_as.h
  bp_me/src/asm/include/bp_cce_inst.h
  bp_me/src/asm/include/bp_common_me_if.h
  bp_me/src/asm/src/bp_as.cc
  bp_me/src/include/c/bp_cce.h
  bp_me/src/include/v/bp_cce_inst.vh
  bp_me/src/include/v/bp_me_pkg.vh
  bp_me/src/v/cache/bp_me_cache_dma_to_cce.v
  bp_me/src/v/cache/bp_me_cache_slice.v
  bp_me/src/v/cache/bp_me_cce_to_cache.v
  bp_me/src/v/cache/bp_me_cce_to_cache_dma.v
  bp_me/src/v/cce/bp_cce.v
  bp_me/src/v/cce/bp_cce_fsm.v
  bp_me/src/v/cce/bp_cce_fsm_top.v
  bp_me/src/v/cce/bp_cce_loopback.v
  bp_me/src/v/cce/bp_cce_msg.v
  bp_me/src/v/cce/bp_cce_reg.v
  bp_me/src/v/cce/bp_cce_src_sel.v
  bp_me/src/v/cce/bp_cce_wrapper.v
  bp_me/src/v/cce/bp_io_cce.v
  bp_me/src/v/cce/bp_uce.v
  bp_me/src/v/wormhole/bp_me_cce_to_mem_link_bidir.v
  bp_me/src/v/wormhole/bp_me_cce_to_mem_link_client.v
  bp_me/src/v/wormhole/bp_me_cce_to_mem_link_master.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_cmd.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_resp.v
  bp_me/test/common/bp_cce_mmio_cfg_loader.v
  bp_me/test/common/bp_me_nonsynth_cce_tracer.v
  bp_me/test/common/bp_mem.v
  bp_me/test/common/bp_mem_nonsynth_tracer.v
  bp_me/test/common/bp_mem_transducer.v
  bp_me/test/tb/bp_cce/testbench.v
  bp_me/test/tb/bp_cce/wrapper.v
  bp_top/src/v/bp_cacc_tile.v
  bp_top/src/v/bp_cacc_vdp.v
  bp_top/src/v/bp_cfg.v
  bp_top/src/v/bp_clint_slice.v
  bp_top/src/v/bp_io_link_to_lce.v
  bp_top/src/v/bp_io_tile.v
  bp_top/src/v/bp_l2e_tile.v
  bp_top/src/v/bp_sacc_tile.v
  bp_top/src/v/bp_sacc_vdp.v
  bp_top/src/v/bp_tile.v
  bp_top/src/v/bp_unicore.v
  bp_top/test/common/bp_nonsynth_host.v
  bp_top/test/common/bp_nonsynth_if_verif.v
  bp_top/test/common/bp_nonsynth_nbf_loader.v
  bp_top/test/tb/bp_tethered/testbench.v
  bp_top/test/tb/bp_tethered/wrapper.v
Labels: update

#592 Fixing I/O cmd/resp width to fill width
  bp_top/src/v/bp_unicore.v
  bp_top/test/tb/bp_tethered/wrapper.v
Labels: bug
