Repository black-parrot/black-parrot, pull requests merged in 2020-10, with the labels that each got.

#629 Adding I$ miss message and backend infrastructure
  bp_be/src/include/bp_be_ctl_defines.vh
  bp_be/src/include/bp_be_internal_if_defines.vh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
  bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.v
  bp_be/src/v/bp_be_checker/bp_be_director.v
  bp_be/src/v/bp_be_mem/bp_be_csr.v
  bp_common/src/include/bp_common_fe_be_if.vh
  bp_common/src/v/bp_tlb.v
  bp_fe/src/v/bp_fe_mem.v
Labels: enhancement

#636 Fix Bootrom flow with Checkpointing
  .gitlab-ci.yml
  bp_common/software/py/nbf.py
  ci/checkpoint.sh
Labels: bug, flow

#638 override bootrom by default for bp_top sim
  bp_top/test/tb/bp_tethered/Makefile.vcs
  bp_top/test/tb/bp_tethered/Makefile.verilator
Labels: bug, flow

#640 bootrom build fixes
  bp_common/test/src/bootrom/Makefile
  bp_top/test/tb/bp_tethered/Makefile.vcs
  bp_top/test/tb/bp_tethered/Makefile.verilator
Labels: bug

#642 Adding psample target to CI
  .gitlab-ci.yml
  bp_top/test/tb/bp_tethered/Makefile.testlist
  ci/checkpoint.sh
Labels: testing

#639 Updating tracers to be more dynamic
  bp_be/test/common/bp_be_nonsynth_npc_tracer.v
  bp_be/test/tb/bp_be_dcache/testbench.v
  bp_fe/test/tb/bp_fe_icache/testbench.v
  bp_top/test/common/bp_nonsynth_branch_profiler.v
  bp_top/test/common/bp_nonsynth_cache_tracer.v
  bp_top/test/common/bp_nonsynth_cosim.v
  bp_top/test/common/bp_nonsynth_host.v
  bp_top/test/common/bp_nonsynth_pc_profiler.v
  bp_top/test/common/bp_nonsynth_perf.v
  bp_top/test/common/bp_nonsynth_vm_tracer.v
  bp_top/test/tb/bp_tethered/Makefile.params
  bp_top/test/tb/bp_tethered/Makefile.verilator
  bp_top/test/tb/bp_tethered/flist.vcs
  bp_top/test/tb/bp_tethered/testbench.v
Labels: enhancement, software

#644 Updating dev to sw dev
  .gitlab-ci.yml
  bp_be/test/common/bp_be_nonsynth_npc_tracer.v
  bp_be/test/tb/bp_be_dcache/testbench.v
  bp_fe/test/tb/bp_fe_icache/testbench.v
  bp_top/test/common/bp_nonsynth_branch_profiler.v
  bp_top/test/common/bp_nonsynth_cache_tracer.v
  bp_top/test/common/bp_nonsynth_cosim.v
  bp_top/test/common/bp_nonsynth_host.v
  bp_top/test/common/bp_nonsynth_pc_profiler.v
  bp_top/test/common/bp_nonsynth_perf.v
  bp_top/test/common/bp_nonsynth_vm_tracer.v
  bp_top/test/common/dromajo_cosim.cpp
  bp_top/test/tb/bp_tethered/Makefile.params
  bp_top/test/tb/bp_tethered/Makefile.vcs
  bp_top/test/tb/bp_tethered/Makefile.verilator
  bp_top/test/tb/bp_tethered/flist.vcs
  bp_top/test/tb/bp_tethered/testbench.v
  ci/checkpoint.sh
Labels: update

#651 Fixing initialization statement and defaults for bp_mem
  bp_me/src/v/cache/bp_me_cache_dma_to_cce.v
  bp_me/test/common/bp_mem.v
Labels: bug
