Repository black-parrot/black-parrot, pull requests merged in 2020-02, with the labels that each got.

#314 A number of unrelated fixes to FE and BE
  bp_be/src/v/bp_be_mem/bp_be_csr.v
  bp_be/src/v/bp_be_mem/bp_be_mem_top.v
  bp_common/src/include/bp_common_csr_defines.vh
  bp_common/src/v/bp_pma.v
  bp_fe/src/v/bp_fe_mem.v
Labels: bug

#307 Dispatch packets should be poisoned instead of flushing to be dequeued from FE queue
  bp_be/src/include/bp_be_internal_if_defines.vh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
  bp_be/src/v/bp_be_checker/bp_be_scheduler.v
  bp_be/src/v/bp_be_mem/bp_be_csr.v
  bp_be/src/v/bp_be_mem/bp_be_mem_top.v
  bp_common/src/include/bp_common_pkg.vh
  bp_top/src/v/bp_clint_slice.v
  bp_top/syn/flist.vcs
Labels: WIP, bug

#320 Changing interface handshake on cce cmd outputs
  bp_me/src/v/cce/bp_cce.v
  bp_me/src/v/cce/bp_cce_msg.v
  bp_me/src/v/cce/bp_cce_msg_cached.v
Labels: bug

#321 Filter out core id when address matching in clint slice
  bp_top/src/v/bp_clint_slice.v
Labels: bug

#322 Moving fence signals into trap packet
  bp_be/src/include/bp_be_internal_if_defines.vh
  bp_be/src/v/bp_be_checker/bp_be_checker_top.v
  bp_be/src/v/bp_be_checker/bp_be_director.v
  bp_be/src/v/bp_be_mem/bp_be_csr.v
  bp_be/src/v/bp_be_mem/bp_be_mem_top.v
  bp_be/src/v/bp_be_top.v
  bp_common/syn/Makefile.verilator
Labels: clarity

#333 Adding autotrigger for CI
  .gitlab-ci.yml
  Makefile
Labels: flow, qol

#336 Fixes for verilator cosim build
  bp_common/syn/Makefile.verilator
  bp_top/test/common/bp_nonsynth_cosim.v
  bp_top/test/tb/bp_top_trace_demo/testbench.v
Labels: bug, flow

#344 Removing wormhole streamers from flist
  bp_top/syn/flist.vcs
Labels: bug

#345 Fixing inferred latches
  .gitlab-ci.yml
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce_req.v
  bp_fe/src/v/bp_fe_lce_req.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_cmd.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_resp.v
Labels: bug
