Repository black-parrot/black-parrot, pull requests merged in 2020-06, with the labels that each got.

#529 Minor Documentation Edit: LCE-CCE Interface
  docs/interface_specification.md
Labels: clarity

#540 Cleanup BE dev in prep for future changes
  bp_be/src/include/bp_be_ctl_defines.vh
  bp_be/src/include/bp_be_internal_if_defines.vh
  bp_be/src/include/bp_be_mem_defines.vh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
  bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_ctrl.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_int.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.v
  bp_be/src/v/bp_be_checker/bp_be_checker_top.v
  bp_be/src/v/bp_be_checker/bp_be_detector.v
  bp_be/src/v/bp_be_checker/bp_be_director.v
  bp_be/src/v/bp_be_checker/bp_be_scheduler.v
  bp_be/src/v/bp_be_mem/bp_be_csr.v
  bp_be/src/v/bp_be_mem/bp_be_mem_top.v
  bp_be/src/v/bp_be_mem/bp_be_ptw.v
  bp_be/src/v/bp_be_top.v
  bp_be/syn/flist.vcs
  bp_be/test/common/bp_be_nonsynth_vm_tracer.v
  bp_common/src/include/bp_common_fe_be_if.vh
  bp_common/src/include/bp_common_rv64_pkg.vh
  bp_fe/syn/flist.vcs
  bp_fe/test/common/mock/mock_be_trace.v
  bp_me/src/v/manycore/bp_me_cce_to_manycore_link.v
  bp_me/src/v/manycore/bp_me_cce_to_manycore_link_config.v
  bp_me/src/v/manycore/bp_me_cce_to_manycore_link_rx.v
  bp_me/src/v/manycore/bp_me_cce_to_manycore_link_tx.v
  bp_top/src/v/bp_cacc_vdp.v
  bp_top/src/v/bp_clint.v
  bp_top/src/v/bp_clint_node.v
  bp_top/src/v/bp_clint_slice.v
  bp_top/syn/flist.vcs
Labels: clarity

#539 Partial Fill / Eviction Cache Service Interface Modification
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
  bp_be/src/v/bp_be_mem/bp_be_mem_top.v
  bp_be/src/v/bp_be_top.v
  bp_be/syn/flist.vcs
  bp_be/test/tb/bp_be_dcache/testbench.v
  bp_be/test/tb/bp_be_dcache/wrapper.v
  bp_common/src/include/bp_common_aviary_defines.vh
  bp_common/src/include/bp_common_aviary_pkg.vh
  bp_common/src/include/bp_common_cache_service_if.vh
  bp_fe/src/v/bp_fe_icache.v
  bp_fe/src/v/bp_fe_mem.v
  bp_fe/src/v/bp_fe_pc_gen.v
  bp_fe/src/v/bp_fe_top.v
  bp_fe/syn/flist.vcs
  bp_fe/test/tb/bp_fe_icache/testbench.v
  bp_fe/test/tb/bp_fe_icache/wrapper.v
  bp_me/src/v/cce/bp_uce.v
  bp_me/src/v/lce/bp_lce.v
  bp_me/src/v/lce/bp_lce_cmd.v
  bp_me/src/v/lce/bp_lce_req.v
  bp_top/src/v/bp_cacc_vdp.v
  bp_top/src/v/bp_core.v
  bp_top/src/v/bp_core_minimal.v
  bp_top/src/v/bp_unicore.v
  bp_top/syn/Makefile
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_cache_tracer.v
  bp_top/test/common/bp_nonsynth_if_verif.v
  bp_top/test/tb/bp_tethered/testbench.v
Labels: enhancement

#546 Cache engine PPA fixes
  bp_me/src/v/cce/bp_uce.v
  bp_me/src/v/lce/bp_lce.v
  bp_me/src/v/lce/bp_lce_cmd.v
  bp_me/src/v/lce/bp_lce_req.v
Labels: ppa_medium

#554 Update FE dev
  bp_be/test/common/bp_be_nonsynth_vm_tracer.v
  bp_common/src/v/bp_tlb.v
  bp_fe/src/v/bp_fe_icache.v
  bp_fe/src/v/bp_fe_mem.v
  bp_top/test/common/bp_nonsynth_cache_tracer.v
  bp_top/test/tb/bp_tethered/testbench.v
Labels: update

#559 Updating dev with be_dev
  bp_be/src/include/bp_be_ctl_defines.vh
  bp_be/src/include/bp_be_internal_if_defines.vh
  bp_be/src/include/bp_be_mem_defines.vh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
  bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_ctrl.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_int.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.v
  bp_be/src/v/bp_be_checker/bp_be_checker_top.v
  bp_be/src/v/bp_be_checker/bp_be_detector.v
  bp_be/src/v/bp_be_checker/bp_be_director.v
  bp_be/src/v/bp_be_checker/bp_be_scheduler.v
  bp_be/src/v/bp_be_mem/bp_be_csr.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_wbuf.v
  bp_be/src/v/bp_be_mem/bp_be_mem_top.v
  bp_be/src/v/bp_be_mem/bp_be_ptw.v
  bp_be/src/v/bp_be_top.v
  bp_be/syn/flist.vcs
  bp_be/test/common/bp_be_nonsynth_npc_tracer.v
  bp_be/test/common/bp_be_nonsynth_vm_tracer.v
  bp_be/test/tb/bp_be_dcache/wrapper.v
  bp_common/src/include/bp_common_cache_service_if.vh
  bp_common/src/include/bp_common_csr_defines.vh
  bp_common/src/include/bp_common_fe_be_if.vh
  bp_common/src/include/bp_common_rv64_pkg.vh
  bp_fe/src/v/bp_fe_icache.v
  bp_fe/syn/flist.vcs
  bp_fe/test/common/mock/mock_be_trace.v
  bp_me/src/v/cache/bp_me_cache_dma_to_cce.v
  bp_me/src/v/cce/bp_cce_dir_segment.v
  bp_me/src/v/cce/bp_uce.v
  bp_me/src/v/lce/bp_lce.v
  bp_me/src/v/lce/bp_lce_cmd.v
  bp_me/src/v/lce/bp_lce_req.v
  bp_me/src/v/manycore/bp_me_cce_to_manycore_link.v
  bp_me/src/v/manycore/bp_me_cce_to_manycore_link_config.v
  bp_me/src/v/manycore/bp_me_cce_to_manycore_link_rx.v
  bp_me/src/v/manycore/bp_me_cce_to_manycore_link_tx.v
  bp_top/src/v/bp_cacc_vdp.v
  bp_top/src/v/bp_clint.v
  bp_top/src/v/bp_clint_node.v
  bp_top/src/v/bp_clint_slice.v
  bp_top/src/v/bp_core.v
  bp_top/src/v/bp_core_minimal.v
  bp_top/src/v/bp_unicore.v
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_core_profiler.v
  bp_top/test/tb/bp_tethered/testbench.v
Labels: update
