Repository black-parrot/black-parrot, pull requests merged in 2020-03, with the labels that each got.

#337 Support FPGA Testbench
  bp_me/src/v/cache/bp_me_cce_to_cache_dma.v
  bp_me/src/v/cce/bp_cce_dir.v
Labels: enhancement, flow

#367 Adding fix to tracers for verilator compilation
  bp_be/test/common/bp_be_nonsynth_calc_tracer.v
  bp_be/test/common/bp_be_nonsynth_dcache_tracer.v
  bp_be/test/common/bp_be_nonsynth_npc_tracer.v
  bp_be/test/common/bp_be_nonsynth_vm_tracer.v
  bp_common/syn/Makefile.verilator
  bp_me/test/common/bp_cce_nonsynth_tracer.v
  bp_top/test/common/bp_nonsynth_commit_tracer.v
Labels: bug

#375 Removing class branch from instructions
  README.md
  docs/getting_started.md
Labels: clarity

#384 Disabling tlb lookup on fencei instructions
  bp_be/src/v/bp_be_mem/bp_be_mem_top.v
Labels: bug

#387 Nonsynth Host Enhancement
  bp_common/syn/Makefile.common
  bp_top/test/common/bp_nonsynth_host.v
Labels: enhancement

#385 Added default Dromajo cfg file
  bp_common/syn/Makefile.vcs
  bp_common/syn/Makefile.verilator
  bp_common/test/Makefile
  bp_common/test/cfg/cosim.cfg
  bp_top/test/tb/bp_processor/testbench.v
  bp_top/test/tb/bp_softcore/testbench.v
Labels: flow

#389 Fixing accidental Verilator pragma
  bp_top/test/common/bp_nonsynth_if_verif.v
  docs/style_guide.md
Labels: bug

#371 Minor updates learned from tapeout
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce_cmd.v
  bp_be/src/v/bp_be_mem/bp_be_mem_top.v
  bp_common/src/include/bp_common_cfg_link_pkg.vh
  bp_common/test/Makefile
  bp_common/test/cfg/cosim.cfg
  bp_fe/src/v/bp_fe_lce_cmd.v
  bp_me/src/v/cce/bp_uce.v
  bp_me/test/common/bp_mem.v
  bp_me/test/common/bp_mem_nonsynth_tracer.v
  bp_me/test/common/bp_mem_transducer.v
  bp_top/src/v/bp_cfg.v
  bp_top/src/v/bp_cfg_buffered.v
  bp_top/src/v/bp_core_complex.v
  bp_top/src/v/bp_io_complex.v
  bp_top/src/v/bp_io_tile.v
  bp_top/src/v/bp_io_tile_node.v
  bp_top/src/v/bp_processor.v
  bp_top/src/v/bp_tile.v
  bp_top/src/v/bp_tile_node.v
  bp_top/test/common/bp_nonsynth_host.v
  bp_top/test/tb/bp_processor/testbench.v
  bp_top/test/tb/bp_processor/wrapper.v
  bp_top/test/tb/bp_softcore/testbench.v
Labels: bug, enhancement

#396 Update FSM CCE for dev
  bp_me/src/v/cce/bp_cce_fsm.v
Labels: qol, testing

#397 Fix be_mem_top Assertion
  bp_be/src/v/bp_be_mem/bp_be_mem_top.v
Labels: enhancement
