Repository black-parrot/black-parrot, pull requests merged in 2020-12, with the labels that each got.

#695 Supporting a direct-mapped D$
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_common/src/include/bp_common_aviary_pkg.sv
Labels: enhancement

#691 Creating a Vivado synthesis flow for BP
  .gitlab-ci.yml
  Makefile.common
  bp_common/syn/Makefile.vivado
  bp_common/syn/tcl/vivado_synth.tcl
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/src/v/bp_sacc_vdp.sv
  bp_top/syn/Makefile
  bp_top/test/tb/bp_tethered/Makefile.vivado
  bp_top/test/tb/bp_tethered/design.xdc
  ci/synth_vivado.sh
Labels: enhancement, flow

#699 Updating dev to sw_dev
  .gitlab-ci.yml
  Makefile.common
  bp_common/syn/Makefile.verilator
  bp_common/syn/Makefile.vivado
  bp_common/syn/tcl/vivado_synth.tcl
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/src/v/bp_sacc_vdp.sv
  bp_top/syn/Makefile
  bp_top/test/common/bp_nonsynth_host.sv
  bp_top/test/common/bp_nonsynth_nbf_loader.sv
  bp_top/test/tb/bp_tethered/Makefile.dc
  bp_top/test/tb/bp_tethered/Makefile.vivado
  bp_top/test/tb/bp_tethered/design.xdc
  bp_top/test/tb/bp_tethered/testbench.sv
  ci/synth_vivado.sh
Labels: update

#705 Fix to scounteren struct definition
  bp_common/src/include/bp_common_csr_defines.svh
Labels: bug

#711 Update dev to fe_dev
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/src/include/bp_common_aviary_pkg.sv
  bp_common/src/include/bp_common_cache_engine_if.svh
  bp_common/src/include/bp_common_core_if.svh
  bp_common/src/v/bp_mmu.sv
  bp_common/src/v/bp_tlb.sv
  bp_common/test/src/bootrom/bootrom.S
  bp_fe/src/include/bp_fe_defines.svh
  bp_fe/src/include/bp_fe_mem_defines.svh
  bp_fe/src/include/bp_fe_pkg.sv
  bp_fe/src/v/bp_fe_icache.sv
  bp_fe/src/v/bp_fe_pc_gen.sv
  bp_fe/src/v/bp_fe_top.sv
  bp_fe/test/tb/bp_fe_icache/Makefile.params
  bp_fe/test/tb/bp_fe_icache/testbench.sv
  bp_fe/test/tb/bp_fe_icache/wrapper.sv
  bp_me/src/v/cce/bp_cce_fsm.sv
  bp_me/src/v/cce/bp_cce_wrapper.sv
  bp_me/src/v/cce/bp_uce.sv
  bp_me/src/v/lce/bp_lce.sv
  bp_me/test/tb/bp_cce/Makefile.dc
  bp_me/test/tb/bp_cce/wrapper.sv
  bp_top/src/v/bp_core.sv
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_cosim.sv
  bp_top/test/common/bp_nonsynth_vm_tracer.sv
  bp_top/test/tb/bp_tethered/Makefile.cfgs
  bp_top/test/tb/bp_tethered/Makefile.dc
  bp_top/test/tb/bp_tethered/Makefile.sv2v
  bp_top/test/tb/bp_tethered/testbench.sv
  bp_top/test/tb/bp_tethered/wrapper.sv
  ci/bloodgraph.sh
  ci/linux.sh
  ci/weird_config.sh
Labels: update

#721 Fixing SAC arbitration in unicore
  bp_top/src/v/bp_unicore.sv
Labels: bug
