Repository black-parrot/black-parrot, pull requests merged in 2020-08, with the labels that each got.

#595 Fixup problems from #560
  bp_be/syn/flist.vcs
  bp_be/test/tb/bp_be_dcache/Makefile.params
  bp_be/test/tb/bp_be_dcache/flist.vcs
  bp_be/test/tb/bp_be_dcache/test_bp.cpp
  bp_be/test/tb/bp_be_dcache/test_bp.v
  bp_be/test/tb/bp_be_dcache/testbench.v
  bp_common/src/v/bsg_bus_pack.v
  bp_fe/src/v/bp_fe_icache.v
  bp_fe/syn/flist.vcs
  bp_fe/test/tb/bp_fe_icache/Makefile.params
  bp_fe/test/tb/bp_fe_icache/flist.vcs
  bp_fe/test/tb/bp_fe_icache/test_bp.cpp
  bp_fe/test/tb/bp_fe_icache/test_bp.v
  bp_fe/test/tb/bp_fe_icache/testbench.v
  bp_me/src/v/cache/bp_me_cce_to_cache.v
  bp_me/syn/flist.vcs
  bp_me/test/common/bp_mem.v
  bp_me/test/common/bp_mem_storage_sync.v
  bp_me/test/common/bp_mem_to_dram.v
  bp_me/test/common/bp_mem_utils.cpp
  bp_me/test/tb/bp_cce/Makefile.params
  bp_me/test/tb/bp_cce/flist.vcs
  bp_me/test/tb/bp_cce/test_bp.cpp
  bp_me/test/tb/bp_cce/test_bp.v
  bp_me/test/tb/bp_cce/testbench.v
  bp_top/syn/flist.vcs
  bp_top/test/tb/bp_tethered/Makefile.params
  bp_top/test/tb/bp_tethered/Makefile.vcs
  bp_top/test/tb/bp_tethered/Makefile.verilator
  bp_top/test/tb/bp_tethered/flist.vcs
  bp_top/test/tb/bp_tethered/testbench.v
Labels: bug

#598 Update README to include ICS talk
  README.md
Labels: clarity

#602 Separate out header / data from wormhole definitions
  bp_me/src/include/v/bp_mem_wormhole.vh
  bp_me/src/v/wormhole/bp_me_cce_to_mem_link_client.v
  bp_me/src/v/wormhole/bp_me_cce_to_mem_link_master.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_cmd.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_req.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_resp.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_cmd.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_resp.v
  bp_top/src/v/bp_cacc_tile.v
  bp_top/src/v/bp_cacc_vdp.v
  bp_top/src/v/bp_io_tile.v
  bp_top/src/v/bp_sacc_tile.v
  bp_top/src/v/bp_sacc_vdp.v
  bp_top/src/v/bp_tile.v
Labels: clarity

#606 add memory credit counter to ucode CCE
  bp_me/src/v/cce/bp_cce_msg.v
Labels: bug

#610 merge me_dev to dev
  bp_me/src/include/v/bp_mem_wormhole.vh
  bp_me/src/v/cce/bp_cce.v
  bp_me/src/v/cce/bp_cce_fsm.v
  bp_me/src/v/cce/bp_cce_inst_stall.v
  bp_me/src/v/cce/bp_cce_msg.v
  bp_me/src/v/cce/bp_uce.v
  bp_me/src/v/wormhole/bp_me_cce_to_mem_link_client.v
  bp_me/src/v/wormhole/bp_me_cce_to_mem_link_master.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_cmd.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_req.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_resp.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_cmd.v
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_resp.v
  bp_top/src/v/bp_cacc_tile.v
  bp_top/src/v/bp_cacc_vdp.v
  bp_top/src/v/bp_io_tile.v
  bp_top/src/v/bp_sacc_tile.v
  bp_top/src/v/bp_sacc_vdp.v
  bp_top/src/v/bp_tile.v
  bp_top/test/tb/bp_tethered/wrapper.v
  docs/interface_specification.md
Labels: update
