Repository black-parrot/black-parrot, pull requests merged in 2020-05, with the labels that each got.

#468 Retime I$ and D$ tag comparison
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
  bp_be/syn/flist.vcs
  bp_fe/src/v/bp_fe_icache.v
Labels: ppa_medium

#473 Fixing the LCE-A$ mem_pkt interface to valid->yumi
  bp_top/src/v/bp_cacc_vdp.v
Labels: bug

#479 Merging be_dev
  bp_be/.gitignore
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce_cmd.v
  bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_wbuf.v
  bp_be/src/v/bp_be_mem/bp_be_mem_top.v
  bp_be/src/v/bp_be_top.v
  bp_be/syn/Makefile
  bp_be/syn/flist.vcs
  bp_be/syn/test.lst
  bp_be/test/tb/bp_be_dcache/Makefile.frag
  bp_be/test/tb/bp_be_dcache/flist.vcs
  bp_be/test/tb/bp_be_dcache/py/Makefile
  bp_be/test/tb/bp_be_dcache/py/trace_script.py
  bp_be/test/tb/bp_be_dcache/testbench.v
  bp_be/test/tb/bp_be_dcache/trace_rom.v
  bp_be/test/tb/bp_be_dcache/wrapper.v
  bp_common/src/include/bp_common_aviary_defines.vh
  bp_common/src/include/bp_common_aviary_pkg.vh
  bp_fe/src/v/bp_fe_icache.v
  bp_fe/src/v/bp_fe_lce.v
  bp_fe/src/v/bp_fe_lce_cmd.v
  bp_fe/src/v/bp_fe_mem.v
  bp_fe/src/v/bp_fe_top.v
  bp_fe/syn/Makefile
  bp_fe/syn/flist.vcs
  bp_fe/syn/test.lst
  bp_fe/test/tb/bp_fe_icache/Makefile.frag
  bp_fe/test/tb/bp_fe_icache/flist.vcs
  bp_fe/test/tb/bp_fe_icache/py/Makefile
  bp_fe/test/tb/bp_fe_icache/py/trace_script.py
  bp_fe/test/tb/bp_fe_icache/testbench.v
  bp_fe/test/tb/bp_fe_icache/wrapper.v
  bp_me/src/v/cache/bp_me_cce_to_cache.v
  bp_me/src/v/cce/bp_uce.v
  bp_top/src/v/bp_cacc_vdp.v
  bp_top/src/v/bp_core.v
  bp_top/src/v/bp_core_minimal.v
  bp_top/src/v/bp_softcore.v
  bp_top/test/common/bp_nonsynth_cache_tracer.v
  bp_top/test/common/bp_nonsynth_if_verif.v
  bp_top/test/tb/bp_processor/testbench.v
  bp_top/test/tb/bp_softcore/testbench.v
Labels: update

#480 Fixed CLINT cmd decoding
  bp_top/src/v/bp_clint_slice.v
Labels: bug

#481 Dev hotfix vivado synthesis
  bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v
  bp_be/src/v/bp_be_calculator/bp_be_pipe_long.v
  bp_be/src/v/bp_be_checker/bp_be_director.v
Labels: bug

#490 Fix poison condition for long latency instructions
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
Labels: bug

#488 Fixing softcore resp arbitration
  bp_top/src/v/bp_softcore.v
Labels: bug

#493 Adding sim dump target. Also adding retry for CI
  .gitlab-ci.yml
  bp_common/syn/Makefile.verilator
Labels: flow

#509 Updating ISA string for M
  bp_be/src/v/bp_be_mem/bp_be_csr.v
Labels: bug

#510 replace |& operator with 2>&1 | for greater compatibility
  bp_common/syn/Makefile.verilator
Labels: flow

#518 Changing softcore to unicore and processor to multicore
  bp_be/syn/flist.vcs
  bp_common/src/include/bp_common_aviary_pkg.vh
  bp_top/src/v/bp_multicore.v
  bp_top/src/v/bp_unicore.v
  bp_top/syn/Makefile
  bp_top/syn/flist.vcs
  bp_top/test/tb/bp_tethered/wrapper.v
  ci/check_design.sh
  ci/example_job.sh
  ci/lint.sh
  ci/single_core_testlist.sh
  docs/getting_started.md
  docs/platform_guide.md
Labels: clarity

#514 Fixing block and nonblocking statements
  bp_top/test/common/bp_nonsynth_branch_profiler.v
Labels: bug

#515 Updating makefiles to play nicer with waveform viewers
  bp_common/syn/Makefile.vcs
  bp_common/syn/Makefile.verilator
Labels: bug, flow

#519 Adding CCE loopback module
  bp_me/src/v/cce/bp_cce_loopback.v
  bp_me/src/v/cce/bp_uce.v
  bp_top/src/v/bp_tile.v
  bp_top/src/v/bp_unicore.v
  bp_top/syn/flist.vcs
Labels: enhancement

#527 Remove defunct pmp csr support
  bp_be/src/v/bp_be_mem/bp_be_csr.v
Labels: bug
