Repository black-parrot/black-parrot, pull requests merged in 2021-04, with the labels that each got.

#827 Improve "lite" make flow
  Makefile
  Makefile.common
Labels: bug, flow

#612 BP Stream Design Between UCE and L2 adapter in unicore
  bp_be/syn/flist.vcs
  bp_be/test/tb/bp_be_dcache/flist.vcs
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/src/include/bp_common_aviary_pkgdef.svh
  bp_common/src/v/bsg_bus_pack.sv
  bp_fe/syn/flist.vcs
  bp_fe/test/tb/bp_fe_icache/flist.vcs
  bp_fe/test/tb/bp_fe_icache/wrapper.sv
  bp_me/src/v/cache/bp_me_cce_to_cache.sv
  bp_me/src/v/cce/bp_uce.sv
  bp_me/src/v/wormhole/bp_burst_to_stream.sv
  bp_me/src/v/wormhole/bp_stream_pump_in.sv
  bp_me/src/v/wormhole/bp_stream_pump_out.sv
  bp_me/src/v/wormhole/bp_stream_to_burst.sv
  bp_me/syn/flist.vcs
  bp_me/test/common/bp_nonsynth_mem.sv
  bp_me/test/tb/bp_cce/flist.vcs
  bp_top/src/v/bp_l2e_tile.sv
  bp_top/src/v/bp_tile.sv
  bp_top/src/v/bp_unicore.sv
  bp_top/syn/Makefile
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_host.sv
  bp_top/test/common/bp_nonsynth_if_verif.sv
Labels: ppa_high

#829 Update dev to top_dev
  bp_top/src/v/bp_unicore.sv
  bp_top/src/v/bp_unicore_lite.sv
  bp_top/syn/flist.vcs
Labels: update

#833 Be more specific on Ubuntu prereq
  docs/getting_started.md
Labels: clarity

#830 Update debug_boot.md
  docs/debug_boot.md
Labels: clarity

#839 Adding NBF read
  bp_common/software/py/nbf.py
  bp_top/src/v/bp_cfg.sv
  bp_top/test/common/bp_nonsynth_cosim.sv
  bp_top/test/common/bp_nonsynth_nbf_loader.sv
  tools/.gitmodules
Labels: enhancement

#816 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/informational.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: clarity

#838 Fix handshake signal names and identify mismatches
  bp_be/test/tb/bp_be_dcache/testbench.sv
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_fe/test/tb/bp_fe_icache/testbench.sv
  bp_fe/test/tb/bp_fe_icache/wrapper.sv
  bp_me/src/v/cache/bp_me_cce_to_cache.sv
  bp_me/src/v/cce/bp_io_cce.sv
  bp_me/src/v/lce/bp_lce.sv
  bp_me/src/v/lce/bp_lce_cmd.sv
  bp_me/src/v/lce/bp_lce_req.sv
  bp_me/src/v/wormhole/bp_me_cce_to_mem_link_bidir.sv
  bp_me/src/v/wormhole/bp_me_cce_to_mem_link_client.sv
  bp_me/src/v/wormhole/bp_me_cce_to_mem_link_master.sv
  bp_me/test/common/bp_me_nonsynth_lce_tracer.sv
  bp_me/test/common/bp_me_nonsynth_mock_lce.sv
  bp_me/test/common/bp_mem_nonsynth_tracer.sv
  bp_me/test/common/bp_nonsynth_mem.sv
  bp_me/test/tb/bp_cce/testbench.sv
  bp_top/src/v/bp_cacc_tile.sv
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/src/v/bp_cfg.sv
  bp_top/src/v/bp_clint_slice.sv
  bp_top/src/v/bp_core.sv
  bp_top/src/v/bp_io_link_to_lce.sv
  bp_top/src/v/bp_io_tile.sv
  bp_top/src/v/bp_l2e_tile.sv
  bp_top/src/v/bp_loopback.sv
  bp_top/src/v/bp_sacc_tile.sv
  bp_top/src/v/bp_tile.sv
  bp_top/src/v/bp_unicore.sv
  bp_top/src/v/bp_unicore_lite.sv
  bp_top/test/common/bp_nonsynth_host.sv
  bp_top/test/common/bp_nonsynth_nbf_loader.sv
  bp_top/test/tb/bp_tethered/testbench.sv
  bp_top/test/tb/bp_tethered/wrapper.sv
  ci/dcache_regress.sh
  ci/icache_regress.sh
  ci/me_regress.sh
  ci/single_core_testlist.sh
Labels: clarity

#845 Add tag and data critical hints
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/src/v/bp_be_top.sv
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_fe/src/v/bp_fe_icache.sv
  bp_fe/src/v/bp_fe_top.sv
  bp_fe/test/tb/bp_fe_icache/wrapper.sv
  bp_me/src/v/cce/bp_uce.sv
  bp_me/src/v/lce/bp_lce.sv
  bp_me/src/v/lce/bp_lce_cmd.sv
  bp_top/src/v/bp_core.sv
  bp_top/src/v/bp_core_minimal.sv
  bp_top/src/v/bp_unicore_lite.sv
  docs/interface_specification.md
Labels: enhancement

#844 Update dev to be_dev
  bp_be/src/include/bp_be_ctl_pkgdef.svh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_csr.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_checker/bp_be_detector.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/src/v/bp_be_top.sv
  bp_be/test/tb/bp_be_dcache/Makefile.params
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/software/py/gendts.py
  bp_fe/src/v/bp_fe_icache.sv
  bp_fe/src/v/bp_fe_top.sv
  bp_fe/test/tb/bp_fe_icache/wrapper.sv
  bp_me/src/v/cce/bp_uce.sv
  bp_me/src/v/lce/bp_lce.sv
  bp_me/src/v/lce/bp_lce_cmd.sv
  bp_me/src/v/lce/bp_lce_req.sv
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/src/v/bp_core.sv
  bp_top/src/v/bp_core_minimal.sv
  bp_top/src/v/bp_l2e_tile.sv
  bp_top/src/v/bp_unicore_lite.sv
  docs/interface_specification.md
Labels: update

#855 add config variable for ucode loading in nbf
  bp_me/test/tb/bp_cce/Makefile.params
  bp_top/test/tb/bp_tethered/Makefile.cfgs
  bp_top/test/tb/bp_tethered/Makefile.params
  bp_top/test/tb/bp_tethered/Makefile.vcs
  bp_top/test/tb/bp_tethered/Makefile.verilator
Labels: flow
