Repository black-parrot/black-parrot, pull requests merged in 2021-09, with the labels that each got.

#919 Refactor L2/dram address swizzle into bp_me_dram_hash module
  bp_be/syn/flist.vcs
  bp_fe/syn/flist.vcs
  bp_me/src/v/dev/bp_me_cce_to_cache.sv
  bp_me/src/v/dev/bp_me_dram_hash_decode.sv
  bp_me/src/v/dev/bp_me_dram_hash_encode.sv
  bp_me/test/common/bp_nonsynth_dram.sv
  bp_me/test/tb/bp_cce/flist.vcs
  bp_top/syn/flist.vcs
Labels: clarity

#899 Parameterized manual retiming for Zynq 7020
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_aux.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
Labels: ppa_high

#921 Minor refactor of PTW
  bp_be/src/include/bp_be_ctl_pkgdef.svh
  bp_be/src/include/bp_be_dcache_pkgdef.svh
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_calculator/bp_be_ptw.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv
  bp_be/src/v/bp_be_top.sv
  bp_be/test/tb/bp_be_dcache/testbench.sv
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/src/v/bsg_deff_reset.v
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/syn/flist.vcs
  bp_top/test/tb/bp_tethered/testbench.sv
Labels: clarity

#926 Fixing up sv2v hardened memories
  bp_common/syn/v/bsg_mem_1rw_sync_mask_write_bit.v
Labels: bug, flow

#932 Converting to bsg_sign_extend
  bp_be/src/v/bp_be_calculator/bp_be_csr.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_int.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
  bp_common/src/include/bp_common_rv64_csr_defines.svh
  bp_fe/src/v/bp_fe_top.sv
  bp_top/test/common/bp_nonsynth_cosim.sv
Labels: clarity

#933 Making cosimulation fifo asynchronous for faster draining
  bp_top/test/common/bp_nonsynth_cosim.sv
  bp_top/test/tb/bp_tethered/testbench.sv
Labels: enhancement, testing

#936 Fix L2 != CCE block width hash function
  bp_common/src/include/bp_common_aviary_defines.svh
  bp_me/src/v/dev/bp_me_cce_to_cache.sv
  bp_me/src/v/dev/bp_me_dram_hash_decode.sv
  bp_me/src/v/dev/bp_me_dram_hash_encode.sv
  bp_me/test/common/bp_nonsynth_dram.sv
Labels: bug
