Repository black-parrot/black-parrot, pull requests merged in 2021-01, with the labels that each got.

#726 Adding RISC-V Summit Talk Link
  README.md
Labels: clarity

#727 Updating docs related to cosimulation
  bp_top/test/tb/bp_tethered/Makefile.testlist
  docs/getting_started.md
  docs/software_guide.md
Labels: clarity

#706 FPGA Signal Alignment Bug
  bp_be/src/v/bp_be_calculator/bp_be_fp_to_rec.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_aux.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
  bp_be/src/v/bp_be_calculator/bp_be_rec_to_fp.sv
Labels: bug

#731 Updating dependency list
  .gitlab-ci.yml
  docs/getting_started.md
Labels: clarity

#732 Hotfixes for cosim
  bp_be/src/v/bp_be_calculator/bp_be_csr.sv
  bp_common/src/include/bp_common_csr_defines.svh
  bp_top/test/tb/bp_tethered/testbench.sv
Labels: bug

#735 Update dev from be dev
  bp_be/src/include/bp_be_internal_if_defines.svh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv
  bp_be/src/v/bp_be_checker/bp_be_detector.sv
  bp_be/src/v/bp_be_checker/bp_be_director.sv
  bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv
  bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
  bp_be/src/v/bp_be_checker/bp_be_scoreboard.sv
  bp_be/src/v/bp_be_top.sv
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_cosim.sv
Labels: update

#740 Fixing watchdog timer to be compatible with VCS 2020
  bp_top/test/common/bp_nonsynth_watchdog.sv
Labels: bug
