Repository black-parrot/black-parrot, pull requests merged in 2021-10, with the labels that each got.

#939 Adding hartid to unicore
  bp_common/src/include/bp_common_aviary_pkgdef.svh
  bp_top/src/v/bp_unicore.sv
  bp_top/src/v/bp_unicore_complex.sv
  bp_top/src/v/bp_unicore_lite.sv
  bp_top/test/common/bp_nonsynth_if_verif.sv
  bp_top/test/tb/bp_tethered/wrapper.sv
Labels: enhancement

#941 Update dev to be_dev
  bp_be/src/include/bp_be_ctl_pkgdef.svh
  bp_be/src/include/bp_be_dcache_pkgdef.svh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_csr.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_aux.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_int.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_calculator/bp_be_ptw.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv
  bp_be/src/v/bp_be_top.sv
  bp_be/test/common/bp_be_nonsynth_dcache_tracer.sv
  bp_be/test/tb/bp_be_dcache/testbench.sv
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/src/include/bp_common_rv64_csr_defines.svh
  bp_common/src/v/bsg_deff_reset.v
  bp_fe/src/v/bp_fe_top.sv
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_cosim.sv
  bp_top/test/tb/bp_tethered/testbench.sv
Labels: update

#942 [WIP] Updating D$ posedge->negedge handshakes
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv
  bp_be/syn/flist.vcs
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/src/v/bsg_dff_reset_half.v
  bp_common/syn/Makefile.dc
  bp_common/syn/Makefile.vcs
  bp_common/syn/Makefile.verilator
  bp_common/syn/tcl/dc_elab.tcl
  bp_fe/syn/flist.vcs
  bp_me/src/v/cce/bp_uce.sv
  bp_me/src/v/lce/bp_lce.sv
  bp_me/src/v/lce/bp_lce_req.sv
  bp_me/syn/flist.vcs
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/src/v/bp_core.sv
  bp_top/src/v/bp_unicore_lite.sv
  bp_top/syn/flist.vcs
Labels: ppa_medium, clarity

#947 fix LCE uncached store overflow - #945
  bp_me/src/v/lce/bp_lce_req.sv
Labels: bug

#949 Update dev to top_dev
  bp_common/src/include/bp_common_aviary_pkgdef.svh
  bp_top/src/v/bp_unicore.sv
  bp_top/src/v/bp_unicore_complex.sv
  bp_top/src/v/bp_unicore_lite.sv
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_if_verif.sv
  bp_top/test/tb/bp_tethered/wrapper.sv
Labels: update

#955 Update bedrock_guide.md
  docs/bedrock_guide.md
Labels: clarity
