Repository black-parrot/black-parrot, pull requests merged in 2021-12, with the labels that each got.

#976 update FSM CCE to MOESIF protocol
  bp_me/src/v/cce/bp_cce_fsm.sv
  bp_me/test/tb/bp_cce/Makefile.params
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/test/tb/bp_tethered/Makefile.params
  ci/me_regress.sh
Labels: bug, enhancement

#977 Adding reset_i X gate to assertions
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv
  bp_me/src/v/cce/bp_cce_dir.sv
  bp_me/src/v/cce/bp_cce_fsm.sv
  bp_me/src/v/cce/bp_cce_reg.sv
  bp_me/src/v/cce/bp_uce.sv
  bp_me/src/v/dev/bp_me_bedrock_register.sv
  bp_me/src/v/dev/bp_me_cce_to_cache.sv
  bp_me/src/v/network/axi_fifo.sv
  bp_me/src/v/network/bp_me_axil_master.sv
  bp_me/test/common/bp_me_nonsynth_lce_tracer.sv
  bp_me/test/common/bp_me_nonsynth_mock_lce.sv
  bp_top/test/common/bp_nonsynth_nbf_loader.sv
  bp_top/test/common/bp_nonsynth_watchdog.sv
Labels: bug, clarity

#974 Fix inferred latches
  bp_me/src/v/network/bp_me_axil_client.sv
  bp_me/src/v/network/bp_me_axil_master.sv
Labels: bug

#975 Fixing behavior for zero gigapage support
  bp_common/src/v/bp_tlb.sv
Labels: bug

#984 Read BTB and BHT even if processing an IF2 override
  bp_fe/src/v/bp_fe_pc_gen.sv
Labels: bug

#993 Enabling L1 atomics for BP unicore
  bp_be/src/include/bp_be_dcache_pkgdef.svh
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/src/include/bp_common_aviary_pkgdef.svh
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/test/common/bp_nonsynth_cosim.sv
  bp_top/test/common/bp_nonsynth_if_verif.sv
  bp_top/test/tb/bp_tethered/Makefile.cfgs
  bp_top/test/tb/bp_tethered/Makefile.testlist
  bp_top/test/tb/bp_tethered/testbench.sv
  ci/single_core_atomics.sh
Labels: enhancement

#992 Fix fflags hazards
  bp_be/src/include/bp_be_defines.svh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
  bp_be/src/v/bp_be_checker/bp_be_detector.sv
  bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv
  bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
  bp_be/src/v/bp_be_top.sv
  bp_common/src/include/bp_common_aviary_pkgdef.svh
Labels: bug
