Repository black-parrot/black-parrot, pull requests merged in 2021-02, with the labels that each got.

#754 Switching translation more gracefully in the MMU
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv
  bp_common/src/include/bp_common_aviary_defines.svh
  bp_common/src/v/bp_mmu.sv
  bp_top/test/common/bp_nonsynth_watchdog.sv
Labels: bug

#755 Minimizing cache tags
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/src/v/bp_be_top.sv
  bp_common/src/include/bp_common_aviary_defines.svh
  bp_common/src/include/bp_common_aviary_pkgdef.svh
  bp_fe/src/v/bp_fe_icache.sv
  bp_fe/src/v/bp_fe_top.sv
  bp_me/src/v/cache/bp_me_cache_slice.sv
  bp_me/src/v/cache/bp_me_cce_to_cache.sv
  bp_me/src/v/cce/bp_cce_dir.sv
  bp_me/src/v/cce/bp_cce_dir_segment.sv
  bp_me/src/v/cce/bp_cce_fsm.sv
  bp_me/src/v/cce/bp_uce.sv
  bp_me/src/v/lce/bp_lce.sv
  bp_me/src/v/lce/bp_lce_cmd.sv
  bp_me/src/v/lce/bp_lce_req.sv
  bp_top/src/v/bp_core.sv
  bp_top/src/v/bp_core_minimal.sv
  bp_top/src/v/bp_unicore.sv
  bp_top/test/common/bp_nonsynth_cache_tracer.sv
  bp_top/test/common/bp_nonsynth_if_verif.sv
Labels: ppa_high

#762 Updating dev to sw_dev
  bp_top/test/common/bp_nonsynth_cosim.sv
Labels: update

#759 Blocks interrupts on pending cache replay
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_checker/bp_be_detector.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/src/v/bp_be_top.sv
Labels: bug

#771 Adding wormhole streamers and passthrough_dynamic PISO/SIPOs from bas…
  bp_common/src/v/bsg_parallel_in_serial_out_passthrough_dynamic.v
  bp_common/src/v/bsg_serial_in_parallel_out_passthrough_dynamic.v
  bp_common/src/v/bsg_wormhole_stream_control.v
  bp_common/src/v/bsg_wormhole_stream_in.v
  bp_common/src/v/bsg_wormhole_stream_out.v
Labels: enhancement

#765 Adding AMO subop types and cache req metadata updates
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_common/src/include/bp_common_bedrock_if.svh
  bp_common/src/include/bp_common_bedrock_pkgdef.svh
  bp_common/src/include/bp_common_cache_engine_if.svh
  bp_fe/src/v/bp_fe_icache.sv
  bp_me/src/v/cache/bp_me_cache_slice.sv
  bp_me/src/v/cce/bp_uce.sv
  bp_me/src/v/lce/bp_lce_req.sv
  bp_top/src/v/bp_clint_slice.sv
  bp_top/test/common/bp_nonsynth_cache_tracer.sv
Labels: enhancement

#772 Adding replay on full FE cmd
  bp_be/src/include/bp_be_ctl_pkgdef.svh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv
  bp_be/src/v/bp_be_checker/bp_be_cmd_queue.sv
  bp_be/src/v/bp_be_checker/bp_be_detector.sv
  bp_be/src/v/bp_be_checker/bp_be_director.sv
  bp_be/src/v/bp_be_top.sv
  bp_top/syn/flist.vcs
Labels: bug

#783 Select the correct mem_resp on multiple valid sources
  bp_top/src/v/bp_tile.sv
Labels: bug

#782 Adding L2 atomics
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_common/src/include/bp_common_aviary_pkgdef.svh
  bp_me/src/v/cache/bp_me_cache_slice.sv
  bp_me/src/v/cache/bp_me_cce_to_cache.sv
  bp_me/src/v/cce/bp_uce.sv
  bp_me/test/common/bp_cce_mmio_cfg_loader.sv
  bp_top/test/common/bp_nonsynth_if_verif.sv
  bp_top/test/common/bp_nonsynth_nbf_loader.sv
  bp_top/test/tb/bp_tethered/Makefile.cfgs
Labels: enhancement

#769 Remove Buffering in lite to burst modules
  bp_me/src/v/wormhole/bp_burst_to_lite.sv
  bp_me/src/v/wormhole/bp_lite_to_burst.sv
  bp_me/src/v/wormhole/bp_lite_to_stream.sv
  bp_top/src/v/bp_unicore.sv
  bp_top/test/tb/bp_tethered/wrapper.sv
Labels: ppa_medium
