Repository black-parrot/black-parrot, pull requests merged in 2021-05, with the labels that each got.

#857 Update dev to top_dev
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_csr.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv
  bp_be/src/v/bp_be_checker/bp_be_detector.sv
  bp_be/src/v/bp_be_checker/bp_be_director.sv
  bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/src/v/bp_be_top.sv
  bp_be/test/tb/bp_be_dcache/Makefile.params
  bp_be/test/tb/bp_be_dcache/testbench.sv
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/software/py/nbf.py
  bp_common/src/include/bp_common_addr_defines.svh
  bp_common/src/include/bp_common_aviary_defines.svh
  bp_common/src/include/bp_common_aviary_pkgdef.svh
  bp_common/src/include/bp_common_cfg_bus_defines.svh
  bp_common/src/include/bp_common_cfg_bus_pkgdef.svh
  bp_common/src/v/bp_mmu.sv
  bp_common/src/v/bp_pma.sv
  bp_fe/src/v/bp_fe_icache.sv
  bp_fe/src/v/bp_fe_top.sv
  bp_fe/test/tb/bp_fe_icache/Makefile.params
  bp_fe/test/tb/bp_fe_icache/testbench.sv
  bp_fe/test/tb/bp_fe_icache/wrapper.sv
  bp_me/src/v/cce/bp_cce.sv
  bp_me/src/v/cce/bp_cce_fsm.sv
  bp_me/src/v/cce/bp_cce_fsm_top.sv
  bp_me/src/v/cce/bp_cce_inst_ram.sv
  bp_me/src/v/cce/bp_cce_msg.sv
  bp_me/src/v/cce/bp_cce_src_sel.sv
  bp_me/src/v/cce/bp_cce_wrapper.sv
  bp_me/src/v/wormhole/bp_me_addr_to_cce_id.sv
  bp_me/test/common/bp_cce_mmio_cfg_loader.sv
  bp_me/test/common/bp_nonsynth_dram.sv
  bp_me/test/tb/bp_cce/Makefile.params
  bp_me/test/tb/bp_cce/testbench.sv
  bp_me/test/tb/bp_cce/wrapper.sv
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/src/v/bp_cfg.sv
  bp_top/src/v/bp_core.sv
  bp_top/src/v/bp_core_complex.sv
  bp_top/src/v/bp_core_minimal.sv
  bp_top/src/v/bp_io_tile.sv
  bp_top/src/v/bp_l2e_tile.sv
  bp_top/src/v/bp_multicore.sv
  bp_top/src/v/bp_sacc_vdp.sv
  bp_top/src/v/bp_tile.sv
  bp_top/src/v/bp_unicore.sv
  bp_top/src/v/bp_unicore_lite.sv
  bp_top/test/common/bp_nonsynth_host.sv
  bp_top/test/common/bp_nonsynth_if_verif.sv
  bp_top/test/tb/bp_tethered/Makefile.cfgs
  bp_top/test/tb/bp_tethered/Makefile.params
Labels: bug, clarity

#859 Fix division to zero bug
  bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
Labels: bug

#860 Update getting_started.md
  docs/getting_started.md
Labels: clarity

#862 Update dev to be_dev
  bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_checker/bp_be_detector.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/syn/flist.vcs
  bp_be/test/tb/bp_be_dcache/testbench.sv
  bp_common/src/v/bsg_dff_reset_half.v
  bp_top/syn/flist.vcs
  bp_top/test/tb/bp_tethered/testbench.sv
Labels: update

#865 Adding 33-bit physical address configs
  bp_common/software/py/nbf.py
  bp_common/src/include/bp_common_aviary_pkgdef.svh
  bp_top/test/common/bp_nonsynth_if_verif.sv
  bp_top/test/common/bp_nonsynth_nbf_loader.sv
  bp_top/test/tb/bp_tethered/Makefile.cfgs
Labels: enhancement

#867 Update CFG addresses
  bp_common/software/py/nbf.py
  bp_common/src/include/bp_common_cfg_bus_pkgdef.svh
  bp_top/src/v/bp_cfg.sv
  docs/platform_guide.md
Labels: clarity

#871 Fix link to simulation repo in README
  README.md
Labels: clarity

#874 merge me_dev to dev - comments and lint fixes
  bp_common/src/include/bp_common_aviary_defines.svh
  bp_common/src/include/bp_common_bedrock_pkgdef.svh
  bp_me/src/include/bp_me_pkg.sv
  bp_me/src/include/bp_me_wormhole_defines.svh
  bp_me/src/v/cache/bp_me_cce_to_cache.sv
  bp_me/src/v/wormhole/bp_me_cord_to_id.sv
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_cmd.sv
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_req.sv
  bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_resp.sv
  bp_top/test/common/bp_nonsynth_nbf_loader.sv
  ci/me_regress.sh
Labels: bug, clarity

#876 Adding validate flag to NBF
  bp_common/software/py/nbf.py
Labels: clarity

#877 Fix cache tracer associativity
  bp_be/test/tb/bp_be_dcache/testbench.sv
  bp_fe/test/tb/bp_fe_icache/testbench.sv
  bp_top/test/common/bp_nonsynth_cache_tracer.sv
  bp_top/test/tb/bp_tethered/testbench.sv
Labels: bug

#878 Fix usage of IF1 state in IF2 branch prediction fallback logic
  bp_fe/src/v/bp_fe_pc_gen.sv
Labels: bug

#880 Reshaping BHT
  bp_common/src/include/bp_common_aviary_defines.svh
  bp_common/src/include/bp_common_aviary_pkgdef.svh
  bp_common/src/v/bsg_mem_1r1w_sync_mask_write_bit_reshape.v
  bp_fe/src/include/bp_fe_defines.svh
  bp_fe/src/v/bp_fe_bht.sv
  bp_fe/src/v/bp_fe_pc_gen.sv
  bp_fe/src/v/bp_fe_top.sv
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_if_verif.sv
Labels: ppa_high

#882 Fixing pred idx width
  bp_fe/src/v/bp_fe_bht.sv
Labels: bug
