Repository black-parrot/black-parrot, pull requests merged in 2022-08, with the labels that each got.

#1102 Fixes for XSIM and NBF
  .github/PULL_REQUEST_TEMPLATE.md
  bp_be/src/v/bp_be_calculator/bp_be_nan_unbox.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_aux.sv
  bp_common/software/py/nbf.py
  bp_fe/src/v/bp_fe_btb.sv
  bp_top/test/common/bp_nonsynth_cosim.sv
  bp_top/test/tb/bp_tethered/Makefile.params
  bp_top/test/tb/bp_tethered/Makefile.vcs
  bp_top/test/tb/bp_tethered/Makefile.verilator
Labels: clarity

#1103 Fix cfg bus addressing to be 64b
  bp_common/software/py/nbf.py
  bp_common/src/include/bp_common_cfg_bus_pkgdef.svh
Labels: clarity

#1105 Mask WAW hazards when issuing exceptions
  bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv
  bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
Labels: bug

#1109 Fixing timing loop and clarifying vaddr injection
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv
  bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
Labels: bug

#1110 Support MULH
  bp_be/src/include/bp_be_ctl_pkgdef.svh
  bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
  bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv
  bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv
  bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_if_verif.sv
  bp_top/test/common/dromajo_cosim.cpp
Labels: enhancement

#1112 Clarification for FE<->BE interface
  bp_be/src/v/bp_be_checker/bp_be_director.sv
  bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv
  bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
  bp_common/src/include/bp_common_core_if.svh
  bp_common/src/include/bp_common_core_pkgdef.svh
  bp_fe/src/v/bp_fe_top.sv
  bp_top/test/common/bp_nonsynth_branch_profiler.sv
  docs/interface_specification.md
Labels: clarity

#1114 Fix accidental wbuf delay, causing data mem hazards
  bp_be/src/include/bp_be_ctl_pkgdef.svh
  bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv
Labels: bug

#1106 Refactor fill network / cmd network multiplexing
  bp_be/syn/flist.vcs
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/src/include/bp_common_bedrock_if.svh
  bp_common/src/include/bp_common_bedrock_pkgdef.svh
  bp_fe/syn/flist.vcs
  bp_me/src/v/lce/bp_lce.sv
  bp_me/src/v/lce/bp_lce_fill.sv
  bp_me/src/v/network/bp_me_xbar_burst.sv
  bp_me/syn/flist.vcs
  bp_top/syn/flist.vcs
  docs/bedrock_guide.md
Labels: ppa_high

#1107 Clean up networking code
  .gitlab-ci.yml
  bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh
  bp_common/src/include/bp_common_aviary_pkgdef.svh
  bp_me/src/v/network/bp_me_bedrock_mem_to_link.sv
  bp_me/src/v/network/bp_me_bedrock_wormhole_header_encode_lce_cmd.sv
  bp_me/src/v/network/bp_me_bedrock_wormhole_header_encode_lce_fill.sv
  bp_me/src/v/network/bp_me_bedrock_wormhole_header_encode_lce_req.sv
  bp_me/src/v/network/bp_me_bedrock_wormhole_header_encode_lce_resp.sv
  bp_me/src/v/network/bp_me_burst_to_wormhole.sv
  bp_me/src/v/network/bp_me_cce_to_mem_link_recv.sv
  bp_me/src/v/network/bp_me_cce_to_mem_link_send.sv
  bp_me/src/v/network/bp_me_wormhole_header_encode.sv
  bp_top/src/v/bp_cacc_tile.sv
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/src/v/bp_io_tile.sv
  bp_top/src/v/bp_l2e_tile.sv
  bp_top/src/v/bp_sacc_loopback.sv
  bp_top/src/v/bp_sacc_scratchpad.sv
  bp_top/src/v/bp_sacc_tile.sv
  bp_top/src/v/bp_sacc_vdp.sv
  bp_top/src/v/bp_tile.sv
  bp_top/syn/flist.vcs
  bp_top/test/tb/bp_tethered/wrapper.sv
  ci/accelerator.sh
Labels: clarity

#1115 Update dev to be_bev
  bp_be/src/include/bp_be_ctl_pkgdef.svh
  bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
  bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv
  bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv
  bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_if_verif.sv
  bp_top/test/common/dromajo_cosim.cpp
Labels: update

#1116 Update dev to fe_dev
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_ctl.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_checker/bp_be_director.sv
  bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv
  bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv
  bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
  bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh
  bp_common/src/include/bp_common_aviary_defines.svh
  bp_common/src/include/bp_common_core_if.svh
  bp_common/src/include/bp_common_core_pkgdef.svh
  bp_fe/src/v/bp_fe_pc_gen.sv
  bp_fe/src/v/bp_fe_top.sv
  bp_fe/test/common/bp_fe_nonsynth_pc_gen_tracer.sv
  bp_top/test/common/bp_nonsynth_branch_profiler.sv
  bp_top/test/common/bp_nonsynth_host.sv
  bp_top/test/tb/bp_tethered/Makefile.params
  bp_top/test/tb/bp_tethered/flist.vcs
  bp_top/test/tb/bp_tethered/testbench.sv
  docs/interface_specification.md
Labels: update

#1108 Adding core lite
  bp_top/src/v/bp_core.sv
  bp_top/src/v/bp_core_complex.sv
  bp_top/src/v/bp_core_lite.sv
  bp_top/src/v/bp_core_tile.sv
  bp_top/src/v/bp_core_tile_node.sv
  bp_top/src/v/bp_unicore.sv
  bp_top/src/v/bp_unicore_complex.sv
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_nbf_loader.sv
  bp_top/test/tb/bp_tethered/testbench.sv
  bp_top/test/tb/bp_tethered/wrapper.sv
Labels: clarity

#1117 Update dev to me_dev
  .gitlab-ci.yml
  bp_be/syn/flist.vcs
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh
  bp_common/src/include/bp_common_aviary_pkgdef.svh
  bp_common/src/include/bp_common_bedrock_if.svh
  bp_common/src/include/bp_common_bedrock_pkgdef.svh
  bp_fe/syn/flist.vcs
  bp_me/src/v/lce/bp_lce.sv
  bp_me/src/v/lce/bp_lce_fill.sv
  bp_me/src/v/network/bp_me_bedrock_mem_to_link.sv
  bp_me/src/v/network/bp_me_bedrock_wormhole_header_encode_lce_cmd.sv
  bp_me/src/v/network/bp_me_bedrock_wormhole_header_encode_lce_fill.sv
  bp_me/src/v/network/bp_me_bedrock_wormhole_header_encode_lce_req.sv
  bp_me/src/v/network/bp_me_bedrock_wormhole_header_encode_lce_resp.sv
  bp_me/src/v/network/bp_me_burst_to_wormhole.sv
  bp_me/src/v/network/bp_me_cce_to_mem_link_recv.sv
  bp_me/src/v/network/bp_me_cce_to_mem_link_send.sv
  bp_me/src/v/network/bp_me_wormhole_header_encode.sv
  bp_me/src/v/network/bp_me_xbar_burst.sv
  bp_me/syn/flist.vcs
  bp_me/test/tb/bp_cce/testbench.sv
  bp_top/src/v/bp_cacc_tile.sv
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/src/v/bp_core.sv
  bp_top/src/v/bp_core_complex.sv
  bp_top/src/v/bp_core_lite.sv
  bp_top/src/v/bp_core_tile.sv
  bp_top/src/v/bp_core_tile_node.sv
  bp_top/src/v/bp_io_tile.sv
  bp_top/src/v/bp_l2e_tile.sv
  bp_top/src/v/bp_sacc_loopback.sv
  bp_top/src/v/bp_sacc_scratchpad.sv
  bp_top/src/v/bp_sacc_tile.sv
  bp_top/src/v/bp_sacc_vdp.sv
  bp_top/src/v/bp_unicore.sv
  bp_top/src/v/bp_unicore_complex.sv
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_nbf_loader.sv
  bp_top/test/tb/bp_tethered/testbench.sv
  bp_top/test/tb/bp_tethered/wrapper.sv
  ci/accelerator.sh
  docs/bedrock_guide.md
Labels: update
