Repository black-parrot/black-parrot, pull requests merged in 2022-02, with the labels that each got.

#1023 Cleanup me_dev
  bp_be/test/tb/bp_be_dcache/testbench.sv
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/src/include/bp_common_aviary_defines.svh
  bp_common/src/include/bp_common_aviary_pkgdef.svh
  bp_fe/test/tb/bp_fe_icache/testbench.sv
  bp_fe/test/tb/bp_fe_icache/wrapper.sv
  bp_me/src/v/cce/bp_cce.sv
  bp_me/src/v/cce/bp_cce_fsm.sv
  bp_me/src/v/cce/bp_cce_msg.sv
  bp_me/src/v/cce/bp_cce_src_sel.sv
  bp_me/src/v/cce/bp_cce_wrapper.sv
  bp_me/src/v/network/bp_me_xbar_stream.sv
  bp_me/src/v/network/bp_me_xbar_stream_buffered.sv
  bp_me/test/common/bp_me_nonsynth_cce_tracer.sv
  bp_me/test/tb/bp_cce/testbench.sv
  bp_me/test/tb/bp_cce/wrapper.sv
  bp_top/src/v/bp_l2e_tile.sv
  bp_top/src/v/bp_tile.sv
  bp_top/src/v/bp_unicore_lite.sv
  bp_top/syn/flist.vcs
  bp_top/test/tb/bp_tethered/testbench.sv
Labels: clarity

#1034 Implement LCE Fill network in BedRock
  bp_be/syn/flist.vcs
  bp_be/test/tb/bp_be_dcache/testbench.sv
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/src/include/bp_common_bedrock_if.svh
  bp_common/src/include/bp_common_bedrock_pkgdef.svh
  bp_fe/syn/flist.vcs
  bp_fe/test/tb/bp_fe_icache/testbench.sv
  bp_fe/test/tb/bp_fe_icache/wrapper.sv
  bp_me/src/v/cce/bp_bedrock_size_to_len.sv
  bp_me/src/v/lce/bp_lce.sv
  bp_me/src/v/lce/bp_lce_cmd.sv
  bp_me/src/v/lce/bp_lce_fill.sv
  bp_me/src/v/network/bp_me_wormhole_packet_encode_lce_fill.sv
  bp_me/syn/flist.vcs
  bp_me/test/common/bp_me_nonsynth_lce_tracer.sv
  bp_me/test/protocol/protocols/mesi.m
  bp_me/test/tb/bp_cce/testbench.sv
  bp_top/src/v/bp_cacc_complex.sv
  bp_top/src/v/bp_cacc_tile.sv
  bp_top/src/v/bp_cacc_tile_node.sv
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/src/v/bp_core.sv
  bp_top/src/v/bp_core_complex.sv
  bp_top/src/v/bp_l2e_tile.sv
  bp_top/src/v/bp_multicore.sv
  bp_top/src/v/bp_tile.sv
  bp_top/src/v/bp_tile_node.sv
  bp_top/syn/flist.vcs
  bp_top/test/tb/bp_tethered/testbench.sv
Labels: bug

#1036 Reducing FMA latency
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_csr.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
  bp_be/src/v/bp_be_checker/bp_be_detector.sv
  docs/platform_guide.md
Labels: enhancement

#1047 Bump top_dev to dev
  bp_be/src/include/bp_be_pkg.sv
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_csr.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv
  bp_be/src/v/bp_be_checker/bp_be_cmd_queue.sv
  bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv
  bp_be/src/v/bp_be_top.sv
  bp_be/test/tb/bp_be_dcache/Makefile.vcs
  bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh
  bp_common/src/include/bp_common_aviary_defines.svh
  bp_common/src/include/bp_common_aviary_pkgdef.svh
  bp_common/src/include/bp_common_clint_pkgdef.svh
  bp_common/src/include/bp_common_defines.svh
  bp_common/src/include/bp_common_pkg.sv
  bp_common/src/v/bsg_bus_pack.sv
  bp_common/test/common/bp_common_test_pkg.sv
  bp_fe/test/tb/bp_fe_icache/Makefile.vcs
  bp_me/src/include/bp_me_cce_inst_pkgdef.svh
  bp_me/src/include/bp_me_pkg.sv
  bp_me/src/v/dev/bp_me_clint_slice.sv
  bp_me/src/v/network/bp_me_axil_master.sv
  bp_me/test/common/bp_me_nonsynth_lce_tracer.sv
  bp_me/test/tb/bp_cce/Makefile.vcs
  bp_me/test/tb/bp_cce/Makefile.verilator
  bp_top/src/include/bp_top_pkg.sv
  bp_top/src/v/bp_axi_top.sv
  bp_top/src/v/bp_core.sv
  bp_top/src/v/bp_core_complex.sv
  bp_top/src/v/bp_core_minimal.sv
  bp_top/src/v/bp_multicore.sv
  bp_top/src/v/bp_tile.sv
  bp_top/src/v/bp_tile_node.sv
  bp_top/src/v/bp_unicore.sv
  bp_top/src/v/bp_unicore_complex.sv
  bp_top/src/v/bp_unicore_lite.sv
  bp_top/syn/flist.vcs
  bp_top/test/common/bp_nonsynth_if_verif.sv
  bp_top/test/common/bp_nonsynth_nbf_loader.sv
  bp_top/test/tb/bp_tethered/testbench.sv
  bp_top/test/tb/bp_tethered/wrapper.sv
Labels: update
