Repository black-parrot/black-parrot, pull requests merged in 2022-03, with the labels that each got.

#1050 Rearranging Unicore/Unicore lite
  bp_top/src/v/bp_unicore.sv
  bp_top/src/v/bp_unicore_lite.sv
Labels: ppa_low, clarity

#1069 Update dev to top_dev
  bp_top/src/v/bp_unicore.sv
  bp_top/src/v/bp_unicore_lite.sv
Labels: update

#1068 fix LCE fill when block size == fill width
  bp_me/src/v/lce/bp_lce_cmd.sv
  bp_me/src/v/lce/bp_lce_fill.sv
Labels: bug

#1070 Clean up Cache Engine Synchronization
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_calculator/bp_be_ptw.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/src/v/bsg_dff_sync_read.v
  bp_fe/test/tb/bp_fe_icache/wrapper.sv
  bp_me/src/v/cce/bp_uce.sv
  bp_me/src/v/lce/bp_lce.sv
  bp_me/src/v/lce/bp_lce_cmd.sv
  bp_me/src/v/lce/bp_lce_fill.sv
  bp_me/src/v/lce/bp_lce_req.sv
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/src/v/bp_core.sv
  bp_top/src/v/bp_core_minimal.sv
  bp_top/src/v/bp_unicore.sv
  bp_top/src/v/bp_unicore_lite.sv
  bp_top/test/tb/bp_tethered/flist.vcs
Labels: ppa_medium, clarity

#1071 Fixing bootrom configurations
  bp_common/software/py/nbf.py
  bp_common/src/include/bp_common_addr_pkgdef.svh
  bp_me/src/v/dev/bp_me_cfg_slice.sv
  bp_me/src/v/network/bp_me_addr_to_cce_id.sv
  bp_top/src/v/bp_io_tile.sv
  bp_top/src/v/bp_unicore.sv
  bp_top/test/common/bp_nonsynth_perf.sv
  bp_top/test/tb/bp_tethered/Makefile.cfgs
  bp_top/test/tb/bp_tethered/Makefile.vcs
  bp_top/test/tb/bp_tethered/Makefile.verilator
Labels: enhancement

#1076 Update dev to be_dev
  bp_be/src/include/bp_be_defines.svh
  bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
  bp_be/src/v/bp_be_calculator/bp_be_csr.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
  bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
  bp_be/src/v/bp_be_calculator/bp_be_ptw.sv
  bp_be/src/v/bp_be_checker/bp_be_detector.sv
  bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
  bp_be/test/tb/bp_be_dcache/wrapper.sv
  bp_common/src/v/bp_mmu.sv
  bp_common/src/v/bsg_dff_sync_read.v
  bp_fe/src/v/bp_fe_top.sv
  bp_fe/test/tb/bp_fe_icache/wrapper.sv
  bp_me/src/v/cce/bp_uce.sv
  bp_me/src/v/lce/bp_lce.sv
  bp_me/src/v/lce/bp_lce_cmd.sv
  bp_me/src/v/lce/bp_lce_fill.sv
  bp_me/src/v/lce/bp_lce_req.sv
  bp_top/src/v/bp_cacc_vdp.sv
  bp_top/src/v/bp_core.sv
  bp_top/src/v/bp_core_minimal.sv
  bp_top/src/v/bp_unicore_lite.sv
  bp_top/test/tb/bp_tethered/flist.vcs
  docs/platform_guide.md
Labels: update

#1077 Update dev to fe_dev
  bp_be/syn/flist.vcs
  bp_common/src/v/bsg_mem_1r1w_sync.v
  bp_common/src/v/bsg_mem_1r1w_sync_synth.v
  bp_fe/src/v/bp_fe_bht.sv
  bp_fe/src/v/bp_fe_btb.sv
  bp_fe/src/v/bp_fe_pc_gen.sv
  bp_fe/syn/flist.vcs
  bp_me/syn/flist.vcs
  bp_top/syn/flist.vcs
Labels: update

#1078 Fixes for bootrom + debug mode merge
  .gitlab-ci.yml
  bp_be/src/v/bp_be_calculator/bp_be_csr.sv
  bp_be/src/v/bp_be_checker/bp_be_cmd_queue.sv
  bp_be/src/v/bp_be_checker/bp_be_director.sv
  bp_be/src/v/bp_be_top.sv
  bp_common/software/py/nbf.py
  bp_me/src/v/dev/bp_me_cache_slice.sv
  bp_me/src/v/lce/bp_lce_cmd.sv
  bp_me/src/v/network/bp_me_addr_to_cce_id.sv
  bp_top/src/v/bp_tile.sv
  bp_top/src/v/bp_unicore.sv
  bp_top/test/tb/bp_tethered/Makefile.vcs
  bp_top/test/tb/bp_tethered/Makefile.verilator
  bp_top/test/tb/bp_tethered/bootrom.dump
  bp_top/test/tb/bp_tethered/bootrom.mem
  bp_top/test/tb/bp_tethered/bootrom.riscv
  bp_top/test/tb/bp_tethered/hello_world.dump
  bp_top/test/tb/bp_tethered/hello_world.mem
  bp_top/test/tb/bp_tethered/hello_world.riscv
  bp_top/test/tb/bp_tethered/testbench.sv
  ci/bootrom.sh
  ci/checkpoint.sh
  ci/linux.sh
  docs/platform_guide.md
Labels: bug
